[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyxodr3d"
version = "0.4.5"
description = "OpenDRIVE 3D viewer and editor. OpenDRIVE to SUMO conversation and vise versa. Converted from libOpenDRIVE (C++)(https://github.com/pageldev/libOpenDRIVE) to Python with multiple additions."
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.10"
license = { file = "LICENSE" }
authors = [
    { name = "Xiangyong Luo", email = "luoxiangyong01@gmail.com" },
]
keywords = [
    "opendrive",
    "xodr",
    "sumo",
    "road-network",
    "traffic-simulation",
    "viewer",
    "3d",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering :: GIS",
    "Topic :: Scientific/Engineering :: Information Analysis",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
    "loguru",
    "matplotlib",
    "pyproj",
    "sumolib",
]

[project.optional-dependencies]
test = [
    "pytest==9.0.3",
]

[project.scripts]
pyxodr3d-sim = "pyxodr3d.sim.cli:main"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["pyxodr3d*"]

[tool.setuptools.package-data]
pyxodr3d = [
    "web/index.html",
    "web/index.css",
    "web/index.js",
    "web/data.xodr",
    "web/README.md",
    "web/viewer.js",
    "web/viewer.wasm",
    "web/viewer.data",
    "web/viewer.local-assets.js",
    "web/favicon.ico",
    "web/static/*",
]
 "pyxodr3d.web" = [
    "index.html",
    "index.css",
    "index.js",
    "data.xodr",
    "README.md",
    "viewer.js",
    "viewer.wasm",
    "viewer.data",
    "viewer.local-assets.js",
    "favicon.ico",
    "static/*",
]

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true
# uv publish --index testpypi
